# Generated by Django 3.1.3 on 2020-11-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_num', models.IntegerField()),
                ('emp_role', models.CharField(max_length=50)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_surname', models.CharField(max_length=50)),
                ('emp_dob', models.DateField()),
                ('emp_salary', models.FloatField()),
                ('emp_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='relation')),
            ],
        ),
    ]
