# Generated by Django 3.1.3 on 2020-11-15 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201115_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='relation'),
        ),
    ]
