# Generated by Django 3.1.3 on 2020-11-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201115_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
