# Generated by Django 3.1.3 on 2020-11-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201115_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
